version: '3'
services: 
  db:
    image: mongo
    build: mongo
    restart: always
    ports: 
      - "27017:27017"
    volumes: 
      - ./mongo/mongo_db:/data/db
    command: mongod
    env_file: ./mongo/.env
  node:
    image: node
    build: node
    ports: 
      - "8080:8080"
    tty: true
    links: 
      - db
    depends_on: 
      - db